config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'reservation/index'
    get 'reservation/show'
    get 'reservation/edit'
  end
  namespace :admin do
    get 'chat_rooms/index'
    get 'chat_rooms/edit'
  end
  namespace :admin do
    get 'calendars/index'
    get 'calendars/new'
    get 'calendars/show'
    get 'calendars/edit'
  end
  namespace :admin do
    get 'homes/top'
  end
  namespace :admin do
    get 'sessions/new'
  end
  
  scope module: 'public' do
    get 'chat_rooms/index'
    get 'chat_rooms/edit'
    get 'reservations/index'
    patch 'reservations/update'
    post 'reservations/create'
    get 'customers/show'
    get 'customers/edit'
    get 'customers/unsubscribe'
    get 'calendars/index'
    get 'calendars/show'
    post 'calendars/create'
    get 'homes/about'
    delete 'reservations/destroy'
    delete 'calendars/:id' => 'calendars#destroy', as: 'calendar_destroy'
    get 'calendars/edit/:id' => 'calendars#edit', as: 'calendar_edit'
    patch 'calendars/:id' => 'calendars#update'
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customer'
    get 'customers/unsubscribe'
    patch 'customers' => 'customers#update', as: 'customer'
    patch 'customers/withdraw'
    get 'homes/index'
    get 'homes/show/:id' => 'homes#show', as: 'public_customer'
  end
  get 'admin/show' => 'admin/homes#show', as: 'admin_customer'
  get 'admin/edit/:id' => 'admin/homes#edit', as: 'admin_customer_edit'
  patch 'admin' => 'admin/homes#update', as: 'admin_customer_update'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  
  root to: 'public/homes#top'
#チャット
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @reservation = Reservation.all
  end
  def show
    @admin = current_admin
    @reservation = current_admin.reservations
    @date1 = Date.current.strftime('%Y/%m/%d')
 #   @date2 = Date.current.next_day.strftime('%Y/%m/%d')
    @date2 = Date.current.next_day
    @date3 = @date2+1
    @date4 = @date3+1
  end

  def edit
#    @admin = Admin.find(params[:id])
    @admin = current_admin
  end

  def update
    @admin = current_admin

    if @admin.update(admin_params)
      flash[:notice]="Customer was successfully updated."
      redirect_to admin_customer_path(@admin)
    else
      render :edit
    end
  end

  private

  def admin_params
    params.require(:admin).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-lx-1">
     <h1>admin info</h1>



      <%= form_with model:@admin, url:admin_customer_update_path, local:true do |f| %>
      <br>
      <label for="inputImage">ProfileImage</label>
      <br>
      <%= attachment_image_tag @admin, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
      <br>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      
     <h3><%= f.label :名前 %></h3>
     <%= f.text_field :name, placeholder:"名前" %>
     <br><br>

     <h3><%= f.label :メールアドレス %></h3>
     <%= f.text_field :email, placeholder:"email" %>
     <br><br>

     <h3><%= f.label :自己紹介 %></h3>
     <%= f.text_field :introduction, placeholder:"自己紹介文" %>
     <br><br>




  <br><br>
  <%= f.submit "Update" %>
<% end %>
</div>
</div>
</div>

app/views/admin/homes/show.html.erb
<div class="container">
  <div class="row">

   <div class="col-md-3">
     <h1>admin info</h1>

<div class="profile-container">
  <%= attachment_image_tag @admin, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
  <hr>

  <th><h3>名前</h3></th>
  <th><h3><%= @admin.name %></h3></th>

  <hr>
 <h3>introduction</h3>
  <h3><%= @admin.introduction %></h3>




  <!--プロフィール変更-->
    <%= link_to admin_customer_edit_path(@admin), class:"btn btn-primary col-xs-5 col-xs-offset-5" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>

</div>
   </div>


    </div>
  </div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-mx-6">
      <h1>予約確認</h1>
        <table class="table imte">
        <th>注文番号</th>
        <th>日付</th>
        <th>時間</th>
        <th></th>
        <th></th>
        <tr>
          <% @reservation.each do |reservation| %>
          <% if reservation.admin_id == current_admin.id %>
          <td><%= reservation.id %></td>
          <td><%= reservation.reservation_date.strftime('%Y/%m/%d') %></td>
          <td>
            <%= form_with model:@reservation, url: calendar_edit_path(reservation), method: :get, local:true  do |f| %>
            <td><%= reservation.time %></td>
            <td><%= f.submit "修正する", class:"btn btn-outline-success"%></td>
          <% end %>
          <% end %>
          </td>
          
        </tr>
        <% end %>
        </table>
    </div>
  </div>
</div>