config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'reservation/index'
    get 'reservation/show'
    get 'reservation/edit'
  end
  namespace :admin do
    get 'chat_rooms/index'
    get 'chat_rooms/edit'
  end
  namespace :admin do
    get 'calendars/index'
    get 'calendars/new'
    get 'calendars/show'
    get 'calendars/edit'
  end
  namespace :admin do
    get 'homes/top'
  end
  namespace :admin do
    get 'sessions/new'
  end
  
  scope module: 'public' do
    get 'chat_rooms/index'
    get 'chat_rooms/edit'
    get 'reservations/index'
    patch 'reservations/update'
    post 'reservations/create'
    get 'customers/show'
    get 'customers/edit'
    get 'customers/unsubscribe'
    get 'calendars/index'
    get 'calendars/show'
    post 'calendars/create'
    get 'homes/about'
    delete 'reservations/destroy'
    delete 'calendars/:id' => 'calendars#destroy', as: 'calendar_destroy'
    get 'calendars/edit/:id' => 'calendars#edit', as: 'calendar_edit'
    patch 'calendars/:id' => 'calendars#update'
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customer'
    get 'customers/unsubscribe'
    patch 'customers' => 'customers#update', as: 'customer'
    patch 'customers/withdraw'
    get 'homes/index'
    get 'homes/show/:id' => 'homes#show', as: 'public_customer'
  end
  get 'admin/show' => 'admin/homes#show', as: 'admin_customer'
  get 'admin/edit/:id' => 'admin/homes#edit', as: 'admin_customer_edit'
  patch 'admin' => 'admin/homes#update', as: 'admin_customer_update'
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  
  root to: 'public/homes#top'
#チャット
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<html>
    <script src="https://kit.fontawesome.com/cc6b65f71c.js" crossorigin="anonymous"></script>
  <head>
    <title>Studuopi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



    </head>
<body>

    <header>
<div class="container">
  <div class="row">
    <div class="col-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#"><%= link_to root_path do %>Studuopi<% end %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
                <!--button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span-->
            </button>


            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <% if customer_signed_in? %>
                <li class="nav-item active">

                </li>
                    <%= link_to homes_index_path, class:"nav-link" do %>
                    <span aria-hidden="true"><i class="fas fa-camera"></i>カメラマン一覧</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to customers_show_path, class:"nav-link" do %>
                    <span aria-hidden="true">マイページ</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to calendars_show_path, class:"nav-link" do %>
                    <span aria-hidden="true">予約確認</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to destroy_customer_session_path, method: :delete, class:"nav-link" do %>
                    <span class="fas fa-sign-out-alt" aria-hidden="true">logout</span>
                    <% end %>
                </li>
            <% elsif admin_signed_in? %>
                <li class="nav-item active">

                </li>
                <li class="nav-item">
                    <i ></i>
                        <%= link_to admin_customer_path, class:"nav-link" do %>
                        <span class="fas fa-home" aria-hidden="true">プロフィール変更</span>
                        <% end %>
                </li>
                <li class="nav-item">

                        <%= link_to admin_homes_top_path, class:"nav-link" do %>
                        <span aria-hidden="true">注文一覧画面</span>
                        <% end %>
                </li>
                <!--
                <li class="nav-item">
                        <%#= link_to admin_items_path, class:"nav-link" do %>
                        <span aria-hidden="true">商品一覧</span>
                        <%# end %>
                </li>
                -->
                <li class="nav-item">
                        <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link" do %>
                        <span class="fas fa-sign-in-alt" aria-hidden="true">admin_logout</span>
                        <% end %>
                </li>
            <% else %>
                <li class="nav-item active">

                </li>
                <li class="nav-item">
                    <i ></i>
                        <%= link_to root_path, class:"nav-link" do %>
                        <span class="fas fa-home" aria-hidden="true">Home</span>
                        <% end %>
                </li>
                <li class="nav-item">

                        <%= link_to homes_about_path, class:"nav-link" do %>
                        <span class="fas fa-link" aria-hidden="true">About</span>
                        <% end %>
                </li>
                <li class="nav-item">
                        <%= link_to new_customer_registration_path, class:"nav-link" do %>
                        <span class="fas fa-user-plus" aria-hidden="true">sign up</span>
                        <% end %>

                </li>
                <li class="nav-item">
                        <%= link_to new_customer_session_path, class:"nav-link" do %>
                        <span class="fas fa-sign-in-alt" aria-hidden="true">login</span>
                        <% end %>
                </li>

            <% end %>
            </ul>
        </div>
    </div>

</nav>
    </div>
  </div>

    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    </header>
    <br>
      <%= yield %>
  </body>

</html>